-- DMS user keybind overrides (edit via Control Center or dms; do not remove this header)

hl.unbind("SUPER + B")
hl.bind("SUPER + B", hl.dsp.exec_cmd("firefox"), { description = "Firefox" })
hl.unbind("SUPER + E")
hl.bind("SUPER + E", hl.dsp.exec_cmd("dolphin"), { description = "dolphin" })
hl.unbind("SUPER + Return")
hl.bind("SUPER + Return", hl.dsp.exec_cmd("alacritty"), { description = "alacritty" })
hl.unbind("SUPER + Backslash")
hl.bind("SUPER + Backslash", hl.dsp.window.close(), { description = "Close window" })
hl.unbind("SUPER + Q")
hl.unbind("SUPER + T")
hl.unbind("SUPER + Slash")
hl.bind("SUPER + Slash", hl.dsp.exec_cmd("sh -c \"/home/josue.ferreira/.opendoor.sh\""), { description = "Opendoor" })
